services:
  api:
    image: phonebook-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    container_name: phonebook-backend-dev
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
